hooks:
    yml_validation:
        paths:
            - '*.yml'
    json_validation:
        paths:
            - '*.json'
    approval_count:
        amount: 1
    owners:
        ownersets:
            general:
                paths:
                    - '*'
                owners:
                    - "@int_admin"
                    - alex-quach-ck
