site_name: Engineering Interview Question Bank
site_description: Bank of standard, approved interview questions for engineers
repo_name: 'ck-private/int_standardized-interview-questions'
repo_url: https://code.corp.creditkarma.com/ck-private/int_standardized-interview-questions
docs_dir: questions
extra:
  repo_icon: github
edit_uri: 'edit/master'

theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'deep purple'
    accent: 'blue'
  # logo:
  #   icon: 'face'

markdown_extensions:
  - codehilite:
      use_pygments: true
  - toc:
      permalink: true

strict: true

extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/syntax.css'
