version: 2
jobs:
  build-docs:
    docker:
      - image: registry.corp.creditkarma.com/ci/mkdocs:12
    steps:
      - checkout
      - run:
          name: Install Template
          command: pip install mkdocs-material
      - run:
          name: Build site
          command: |
            mkdir -p build
            cp -r ./questions ./theme ./mkdocs.yml build
            (cd build && mkdocs build)
      - run:
          name: Publish site
          command: curl -fsSL https://${CIRCLE_OAUTH_TOKEN}:x-oauth-basic@raw.code.corp.creditkarma.com/ck-private/ck_static/master/publish.sh | bash -s eng-interview-questions build/site

workflows:
  version: 2
  release-mkdocs-site:
    jobs:
      - build-docs:
          context: org-global
          filters:
            branches:
              only: /^master/
